# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import numpy as np
import scipy.sparse



from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PyAssembler')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PyAssembler')
    _PyAssembler = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyAssembler', [dirname(__file__)])
        except ImportError:
            import _PyAssembler
            return _PyAssembler
        try:
            _mod = imp.load_module('_PyAssembler', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PyAssembler = swig_import_helper()
    del swig_import_helper
else:
    import _PyAssembler
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class ZSparseMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ZSparseMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ZSparseMatrix, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _PyAssembler.new_ZSparseMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _PyAssembler.delete_ZSparseMatrix
    __del__ = lambda self: None

    def num_rows(self):
        return _PyAssembler.ZSparseMatrix_num_rows(self)

    def num_cols(self):
        return _PyAssembler.ZSparseMatrix_num_cols(self)

    def get_inner_size(self):
        return _PyAssembler.ZSparseMatrix_get_inner_size(self)

    def get_outer_size(self):
        return _PyAssembler.ZSparseMatrix_get_outer_size(self)

    def get_value_size(self):
        return _PyAssembler.ZSparseMatrix_get_value_size(self)

    def get_inner_indices(self, np_idx_array):
        return _PyAssembler.ZSparseMatrix_get_inner_indices(self, np_idx_array)

    def get_outer_indices(self, np_idx_array):
        return _PyAssembler.ZSparseMatrix_get_outer_indices(self, np_idx_array)

    def get_values(self, np_value_array):
        return _PyAssembler.ZSparseMatrix_get_values(self, np_value_array)

    def import_raw_csc(self, num_rows, num_cols, inner_idx_array, outer_idx_array, value_array):
        return _PyAssembler.ZSparseMatrix_import_raw_csc(self, num_rows, num_cols, inner_idx_array, outer_idx_array, value_array)

    def import_raw_coo(self, num_rows, num_cols, row_indices, col_indices, value_array):
        return _PyAssembler.ZSparseMatrix_import_raw_coo(self, num_rows, num_cols, row_indices, col_indices, value_array)
ZSparseMatrix_swigregister = _PyAssembler.ZSparseMatrix_swigregister
ZSparseMatrix_swigregister(ZSparseMatrix)

SHARED_PTR_DISOWN = _PyAssembler.SHARED_PTR_DISOWN
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyAssembler.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _PyAssembler.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PyAssembler.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PyAssembler.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PyAssembler.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PyAssembler.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PyAssembler.SwigPyIterator_copy(self)

    def next(self):
        return _PyAssembler.SwigPyIterator_next(self)

    def __next__(self):
        return _PyAssembler.SwigPyIterator___next__(self)

    def previous(self):
        return _PyAssembler.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PyAssembler.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PyAssembler.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PyAssembler.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PyAssembler.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PyAssembler.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PyAssembler.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PyAssembler.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _PyAssembler.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyAssembler.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyAssembler.vectori___nonzero__(self)

    def __bool__(self):
        return _PyAssembler.vectori___bool__(self)

    def __len__(self):
        return _PyAssembler.vectori___len__(self)

    def __getslice__(self, i, j):
        return _PyAssembler.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyAssembler.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyAssembler.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyAssembler.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyAssembler.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyAssembler.vectori___setitem__(self, *args)

    def pop(self):
        return _PyAssembler.vectori_pop(self)

    def append(self, x):
        return _PyAssembler.vectori_append(self, x)

    def empty(self):
        return _PyAssembler.vectori_empty(self)

    def size(self):
        return _PyAssembler.vectori_size(self)

    def swap(self, v):
        return _PyAssembler.vectori_swap(self, v)

    def begin(self):
        return _PyAssembler.vectori_begin(self)

    def end(self):
        return _PyAssembler.vectori_end(self)

    def rbegin(self):
        return _PyAssembler.vectori_rbegin(self)

    def rend(self):
        return _PyAssembler.vectori_rend(self)

    def clear(self):
        return _PyAssembler.vectori_clear(self)

    def get_allocator(self):
        return _PyAssembler.vectori_get_allocator(self)

    def pop_back(self):
        return _PyAssembler.vectori_pop_back(self)

    def erase(self, *args):
        return _PyAssembler.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _PyAssembler.new_vectori(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyAssembler.vectori_push_back(self, x)

    def front(self):
        return _PyAssembler.vectori_front(self)

    def back(self):
        return _PyAssembler.vectori_back(self)

    def assign(self, n, x):
        return _PyAssembler.vectori_assign(self, n, x)

    def resize(self, *args):
        return _PyAssembler.vectori_resize(self, *args)

    def insert(self, *args):
        return _PyAssembler.vectori_insert(self, *args)

    def reserve(self, n):
        return _PyAssembler.vectori_reserve(self, n)

    def capacity(self):
        return _PyAssembler.vectori_capacity(self)
    __swig_destroy__ = _PyAssembler.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _PyAssembler.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyAssembler.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyAssembler.vectord___nonzero__(self)

    def __bool__(self):
        return _PyAssembler.vectord___bool__(self)

    def __len__(self):
        return _PyAssembler.vectord___len__(self)

    def __getslice__(self, i, j):
        return _PyAssembler.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyAssembler.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyAssembler.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyAssembler.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyAssembler.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyAssembler.vectord___setitem__(self, *args)

    def pop(self):
        return _PyAssembler.vectord_pop(self)

    def append(self, x):
        return _PyAssembler.vectord_append(self, x)

    def empty(self):
        return _PyAssembler.vectord_empty(self)

    def size(self):
        return _PyAssembler.vectord_size(self)

    def swap(self, v):
        return _PyAssembler.vectord_swap(self, v)

    def begin(self):
        return _PyAssembler.vectord_begin(self)

    def end(self):
        return _PyAssembler.vectord_end(self)

    def rbegin(self):
        return _PyAssembler.vectord_rbegin(self)

    def rend(self):
        return _PyAssembler.vectord_rend(self)

    def clear(self):
        return _PyAssembler.vectord_clear(self)

    def get_allocator(self):
        return _PyAssembler.vectord_get_allocator(self)

    def pop_back(self):
        return _PyAssembler.vectord_pop_back(self)

    def erase(self, *args):
        return _PyAssembler.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _PyAssembler.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyAssembler.vectord_push_back(self, x)

    def front(self):
        return _PyAssembler.vectord_front(self)

    def back(self):
        return _PyAssembler.vectord_back(self)

    def assign(self, n, x):
        return _PyAssembler.vectord_assign(self, n, x)

    def resize(self, *args):
        return _PyAssembler.vectord_resize(self, *args)

    def insert(self, *args):
        return _PyAssembler.vectord_insert(self, *args)

    def reserve(self, n):
        return _PyAssembler.vectord_reserve(self, n)

    def capacity(self):
        return _PyAssembler.vectord_capacity(self)
    __swig_destroy__ = _PyAssembler.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _PyAssembler.vectord_swigregister
vectord_swigregister(vectord)

class vectors(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectors, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectors, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyAssembler.vectors_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyAssembler.vectors___nonzero__(self)

    def __bool__(self):
        return _PyAssembler.vectors___bool__(self)

    def __len__(self):
        return _PyAssembler.vectors___len__(self)

    def __getslice__(self, i, j):
        return _PyAssembler.vectors___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyAssembler.vectors___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyAssembler.vectors___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyAssembler.vectors___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyAssembler.vectors___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyAssembler.vectors___setitem__(self, *args)

    def pop(self):
        return _PyAssembler.vectors_pop(self)

    def append(self, x):
        return _PyAssembler.vectors_append(self, x)

    def empty(self):
        return _PyAssembler.vectors_empty(self)

    def size(self):
        return _PyAssembler.vectors_size(self)

    def swap(self, v):
        return _PyAssembler.vectors_swap(self, v)

    def begin(self):
        return _PyAssembler.vectors_begin(self)

    def end(self):
        return _PyAssembler.vectors_end(self)

    def rbegin(self):
        return _PyAssembler.vectors_rbegin(self)

    def rend(self):
        return _PyAssembler.vectors_rend(self)

    def clear(self):
        return _PyAssembler.vectors_clear(self)

    def get_allocator(self):
        return _PyAssembler.vectors_get_allocator(self)

    def pop_back(self):
        return _PyAssembler.vectors_pop_back(self)

    def erase(self, *args):
        return _PyAssembler.vectors_erase(self, *args)

    def __init__(self, *args):
        this = _PyAssembler.new_vectors(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyAssembler.vectors_push_back(self, x)

    def front(self):
        return _PyAssembler.vectors_front(self)

    def back(self):
        return _PyAssembler.vectors_back(self)

    def assign(self, n, x):
        return _PyAssembler.vectors_assign(self, n, x)

    def resize(self, *args):
        return _PyAssembler.vectors_resize(self, *args)

    def insert(self, *args):
        return _PyAssembler.vectors_insert(self, *args)

    def reserve(self, n):
        return _PyAssembler.vectors_reserve(self, n)

    def capacity(self):
        return _PyAssembler.vectors_capacity(self)
    __swig_destroy__ = _PyAssembler.delete_vectors
    __del__ = lambda self: None
vectors_swigregister = _PyAssembler.vectors_swigregister
vectors_swigregister(vectors)

class Mesh(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mesh, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mesh, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyAssembler.delete_Mesh
    __del__ = lambda self: None

    def get_dim(self):
        return _PyAssembler.Mesh_get_dim(self)

    def get_num_vertices(self):
        return _PyAssembler.Mesh_get_num_vertices(self)

    def get_num_faces(self):
        return _PyAssembler.Mesh_get_num_faces(self)

    def get_num_voxels(self):
        return _PyAssembler.Mesh_get_num_voxels(self)

    def get_vertex(self, *args):
        return _PyAssembler.Mesh_get_vertex(self, *args)

    def get_face(self, *args):
        return _PyAssembler.Mesh_get_face(self, *args)

    def get_voxel(self, *args):
        return _PyAssembler.Mesh_get_voxel(self, *args)

    def get_vertices(self, *args):
        return _PyAssembler.Mesh_get_vertices(self, *args)

    def get_faces(self, *args):
        return _PyAssembler.Mesh_get_faces(self, *args)

    def get_voxels(self, *args):
        return _PyAssembler.Mesh_get_voxels(self, *args)

    def get_vertex_per_face(self):
        return _PyAssembler.Mesh_get_vertex_per_face(self)

    def get_vertex_per_voxel(self):
        return _PyAssembler.Mesh_get_vertex_per_voxel(self)

    def enable_connectivity(self):
        return _PyAssembler.Mesh_enable_connectivity(self)

    def enable_vertex_connectivity(self):
        return _PyAssembler.Mesh_enable_vertex_connectivity(self)

    def enable_face_connectivity(self):
        return _PyAssembler.Mesh_enable_face_connectivity(self)

    def enable_voxel_connectivity(self):
        return _PyAssembler.Mesh_enable_voxel_connectivity(self)

    def get_vertex_adjacent_vertices(self, vi):
        return _PyAssembler.Mesh_get_vertex_adjacent_vertices(self, vi)

    def get_vertex_adjacent_faces(self, vi):
        return _PyAssembler.Mesh_get_vertex_adjacent_faces(self, vi)

    def get_vertex_adjacent_voxels(self, vi):
        return _PyAssembler.Mesh_get_vertex_adjacent_voxels(self, vi)

    def get_face_adjacent_faces(self, fi):
        return _PyAssembler.Mesh_get_face_adjacent_faces(self, fi)

    def get_face_adjacent_voxels(self, fi):
        return _PyAssembler.Mesh_get_face_adjacent_voxels(self, fi)

    def get_voxel_adjacent_faces(self, Vi):
        return _PyAssembler.Mesh_get_voxel_adjacent_faces(self, Vi)

    def get_voxel_adjacent_voxels(self, Vi):
        return _PyAssembler.Mesh_get_voxel_adjacent_voxels(self, Vi)

    def has_attribute(self, attr_name):
        return _PyAssembler.Mesh_has_attribute(self, attr_name)

    def add_attribute(self, attr_name):
        return _PyAssembler.Mesh_add_attribute(self, attr_name)

    def remove_attribute(self, attr_name):
        return _PyAssembler.Mesh_remove_attribute(self, attr_name)

    def get_attribute(self, *args):
        return _PyAssembler.Mesh_get_attribute(self, *args)

    def set_attribute(self, attr_name, attr_value):
        return _PyAssembler.Mesh_set_attribute(self, attr_name, attr_value)

    def get_attribute_names(self):
        return _PyAssembler.Mesh_get_attribute_names(self)
Mesh_swigregister = _PyAssembler.Mesh_swigregister
Mesh_swigregister(Mesh)

class Material(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Material, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Material, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyAssembler.Material_create)
    else:
        create = _PyAssembler.Material_create
    if _newclass:
        create_isotropic = staticmethod(_PyAssembler.Material_create_isotropic)
    else:
        create_isotropic = _PyAssembler.Material_create_isotropic
    if _newclass:
        create_symmetric = staticmethod(_PyAssembler.Material_create_symmetric)
    else:
        create_symmetric = _PyAssembler.Material_create_symmetric
    if _newclass:
        create_orthotropic = staticmethod(_PyAssembler.Material_create_orthotropic)
    else:
        create_orthotropic = _PyAssembler.Material_create_orthotropic
    if _newclass:
        create_periodic = staticmethod(_PyAssembler.Material_create_periodic)
    else:
        create_periodic = _PyAssembler.Material_create_periodic
    if _newclass:
        create_element_wise_isotropic = staticmethod(_PyAssembler.Material_create_element_wise_isotropic)
    else:
        create_element_wise_isotropic = _PyAssembler.Material_create_element_wise_isotropic
    if _newclass:
        create_element_wise_orthotropic = staticmethod(_PyAssembler.Material_create_element_wise_orthotropic)
    else:
        create_element_wise_orthotropic = _PyAssembler.Material_create_element_wise_orthotropic
    if _newclass:
        create_element_wise_symmetric = staticmethod(_PyAssembler.Material_create_element_wise_symmetric)
    else:
        create_element_wise_symmetric = _PyAssembler.Material_create_element_wise_symmetric

    def get_material_tensor(self, i, j, k, l, coord):
        return _PyAssembler.Material_get_material_tensor(self, i, j, k, l, coord)

    def strain_to_stress(self, strain, coord):
        return _PyAssembler.Material_strain_to_stress(self, strain, coord)

    def get_density(self, *args):
        return _PyAssembler.Material_get_density(self, *args)

    def get_dim(self):
        return _PyAssembler.Material_get_dim(self)

    def update(self):
        return _PyAssembler.Material_update(self)
    __swig_destroy__ = _PyAssembler.delete_Material
    __del__ = lambda self: None
Material_swigregister = _PyAssembler.Material_swigregister
Material_swigregister(Material)

def Material_create(density, material_tensor):
    return _PyAssembler.Material_create(density, material_tensor)
Material_create = _PyAssembler.Material_create

def Material_create_isotropic(dim, desnity, young, poisson):
    return _PyAssembler.Material_create_isotropic(dim, desnity, young, poisson)
Material_create_isotropic = _PyAssembler.Material_create_isotropic

def Material_create_symmetric(density, material_matrix):
    return _PyAssembler.Material_create_symmetric(density, material_matrix)
Material_create_symmetric = _PyAssembler.Material_create_symmetric

def Material_create_orthotropic(density, young_modulus, poisson_ratio, shear_modulus):
    return _PyAssembler.Material_create_orthotropic(density, young_modulus, poisson_ratio, shear_modulus)
Material_create_orthotropic = _PyAssembler.Material_create_orthotropic

def Material_create_periodic(mat1, mat2, axis, period, ratio, phase):
    return _PyAssembler.Material_create_periodic(mat1, mat2, axis, period, ratio, phase)
Material_create_periodic = _PyAssembler.Material_create_periodic

def Material_create_element_wise_isotropic(density, mesh, young_field_name, poisson_field_name):
    return _PyAssembler.Material_create_element_wise_isotropic(density, mesh, young_field_name, poisson_field_name)
Material_create_element_wise_isotropic = _PyAssembler.Material_create_element_wise_isotropic

def Material_create_element_wise_orthotropic(density, mesh, young_field_names, poisson_field_names, shear_field_names):
    return _PyAssembler.Material_create_element_wise_orthotropic(density, mesh, young_field_names, poisson_field_names, shear_field_names)
Material_create_element_wise_orthotropic = _PyAssembler.Material_create_element_wise_orthotropic

def Material_create_element_wise_symmetric(density, mesh, matrix_field_nmae):
    return _PyAssembler.Material_create_element_wise_symmetric(density, mesh, matrix_field_nmae)
Material_create_element_wise_symmetric = _PyAssembler.Material_create_element_wise_symmetric


def ZSparseMatrix2Scipy(matrix):
    """
    Convert a C++ type ZSparseMatrix to python type scipy.sparse.csc_matrix.
    """
    data = np.ndarray(matrix.get_value_size(), dtype=float);
    outer_idx = np.ndarray(matrix.get_outer_size(), dtype=np.int32);
    inner_idx = np.ndarray(matrix.get_inner_size(), dtype=np.int32);

    matrix.get_values(data);
    matrix.get_outer_indices(outer_idx);
    matrix.get_inner_indices(inner_idx);

    return scipy.sparse.csc_matrix((data, inner_idx, outer_idx),
        shape = (matrix.num_rows(), matrix.num_cols()),
        dtype = float);

class FEAssembler(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FEAssembler, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FEAssembler, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyAssembler.FEAssembler_create)
    else:
        create = _PyAssembler.FEAssembler_create
    if _newclass:
        create_from_name = staticmethod(_PyAssembler.FEAssembler_create_from_name)
    else:
        create_from_name = _PyAssembler.FEAssembler_create_from_name

    def assemble(self, matrix_name):
        return _PyAssembler.FEAssembler_assemble(self, matrix_name)

    def set_material(self, material):
        return _PyAssembler.FEAssembler_set_material(self, material)
    __swig_destroy__ = _PyAssembler.delete_FEAssembler
    __del__ = lambda self: None
FEAssembler_swigregister = _PyAssembler.FEAssembler_swigregister
FEAssembler_swigregister(FEAssembler)

def FEAssembler_create(mesh, material):
    return _PyAssembler.FEAssembler_create(mesh, material)
FEAssembler_create = _PyAssembler.FEAssembler_create

def FEAssembler_create_from_name(mesh, name):
    return _PyAssembler.FEAssembler_create_from_name(mesh, name)
FEAssembler_create_from_name = _PyAssembler.FEAssembler_create_from_name

# This file is compatible with both classic and new-style classes.


