# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PyCGAL')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PyCGAL')
    _PyCGAL = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyCGAL', [dirname(__file__)])
        except ImportError:
            import _PyCGAL
            return _PyCGAL
        try:
            _mod = imp.load_module('_PyCGAL', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PyCGAL = swig_import_helper()
    del swig_import_helper
else:
    import _PyCGAL
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class AABBTree(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AABBTree, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AABBTree, name)
    __repr__ = _swig_repr

    def __init__(self, vertices, faces):
        this = _PyCGAL.new_AABBTree(vertices, faces)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def do_intersect_segments(self, vertices, edges):
        return _PyCGAL.AABBTree_do_intersect_segments(self, vertices, edges)

    def look_up(self, points):
        return _PyCGAL.AABBTree_look_up(self, points)

    def look_up_with_closest_points(self, points):
        return _PyCGAL.AABBTree_look_up_with_closest_points(self, points)
    __swig_destroy__ = _PyCGAL.delete_AABBTree
    __del__ = lambda self: None
AABBTree_swigregister = _PyCGAL.AABBTree_swigregister
AABBTree_swigregister(AABBTree)

class SelfIntersection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SelfIntersection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SelfIntersection, name)
    __repr__ = _swig_repr

    def __init__(self, vertices, faces):
        this = _PyCGAL.new_SelfIntersection(vertices, faces)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def detect_self_intersection(self):
        return _PyCGAL.SelfIntersection_detect_self_intersection(self)

    def clear(self):
        return _PyCGAL.SelfIntersection_clear(self)

    def get_self_intersecting_pairs(self):
        return _PyCGAL.SelfIntersection_get_self_intersecting_pairs(self)

    def handle_intersection_candidate(self, f_idx_1, f_idx_2):
        return _PyCGAL.SelfIntersection_handle_intersection_candidate(self, f_idx_1, f_idx_2)
    __swig_destroy__ = _PyCGAL.delete_SelfIntersection
    __del__ = lambda self: None
SelfIntersection_swigregister = _PyCGAL.SelfIntersection_swigregister
SelfIntersection_swigregister(SelfIntersection)

# This file is compatible with both classic and new-style classes.


