# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PyIGL')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PyIGL')
    _PyIGL = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyIGL', [dirname(__file__)])
        except ImportError:
            import _PyIGL
            return _PyIGL
        try:
            _mod = imp.load_module('_PyIGL', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PyIGL = swig_import_helper()
    del swig_import_helper
else:
    import _PyIGL
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

SHARED_PTR_DISOWN = _PyIGL.SHARED_PTR_DISOWN
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIGL.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _PyIGL.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PyIGL.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PyIGL.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PyIGL.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PyIGL.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PyIGL.SwigPyIterator_copy(self)

    def next(self):
        return _PyIGL.SwigPyIterator_next(self)

    def __next__(self):
        return _PyIGL.SwigPyIterator___next__(self)

    def previous(self):
        return _PyIGL.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PyIGL.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PyIGL.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PyIGL.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PyIGL.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PyIGL.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PyIGL.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PyIGL.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _PyIGL.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIGL.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIGL.vectori___nonzero__(self)

    def __bool__(self):
        return _PyIGL.vectori___bool__(self)

    def __len__(self):
        return _PyIGL.vectori___len__(self)

    def __getslice__(self, i, j):
        return _PyIGL.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIGL.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIGL.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIGL.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIGL.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIGL.vectori___setitem__(self, *args)

    def pop(self):
        return _PyIGL.vectori_pop(self)

    def append(self, x):
        return _PyIGL.vectori_append(self, x)

    def empty(self):
        return _PyIGL.vectori_empty(self)

    def size(self):
        return _PyIGL.vectori_size(self)

    def swap(self, v):
        return _PyIGL.vectori_swap(self, v)

    def begin(self):
        return _PyIGL.vectori_begin(self)

    def end(self):
        return _PyIGL.vectori_end(self)

    def rbegin(self):
        return _PyIGL.vectori_rbegin(self)

    def rend(self):
        return _PyIGL.vectori_rend(self)

    def clear(self):
        return _PyIGL.vectori_clear(self)

    def get_allocator(self):
        return _PyIGL.vectori_get_allocator(self)

    def pop_back(self):
        return _PyIGL.vectori_pop_back(self)

    def erase(self, *args):
        return _PyIGL.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _PyIGL.new_vectori(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyIGL.vectori_push_back(self, x)

    def front(self):
        return _PyIGL.vectori_front(self)

    def back(self):
        return _PyIGL.vectori_back(self)

    def assign(self, n, x):
        return _PyIGL.vectori_assign(self, n, x)

    def resize(self, *args):
        return _PyIGL.vectori_resize(self, *args)

    def insert(self, *args):
        return _PyIGL.vectori_insert(self, *args)

    def reserve(self, n):
        return _PyIGL.vectori_reserve(self, n)

    def capacity(self):
        return _PyIGL.vectori_capacity(self)
    __swig_destroy__ = _PyIGL.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _PyIGL.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIGL.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIGL.vectord___nonzero__(self)

    def __bool__(self):
        return _PyIGL.vectord___bool__(self)

    def __len__(self):
        return _PyIGL.vectord___len__(self)

    def __getslice__(self, i, j):
        return _PyIGL.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIGL.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIGL.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIGL.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIGL.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIGL.vectord___setitem__(self, *args)

    def pop(self):
        return _PyIGL.vectord_pop(self)

    def append(self, x):
        return _PyIGL.vectord_append(self, x)

    def empty(self):
        return _PyIGL.vectord_empty(self)

    def size(self):
        return _PyIGL.vectord_size(self)

    def swap(self, v):
        return _PyIGL.vectord_swap(self, v)

    def begin(self):
        return _PyIGL.vectord_begin(self)

    def end(self):
        return _PyIGL.vectord_end(self)

    def rbegin(self):
        return _PyIGL.vectord_rbegin(self)

    def rend(self):
        return _PyIGL.vectord_rend(self)

    def clear(self):
        return _PyIGL.vectord_clear(self)

    def get_allocator(self):
        return _PyIGL.vectord_get_allocator(self)

    def pop_back(self):
        return _PyIGL.vectord_pop_back(self)

    def erase(self, *args):
        return _PyIGL.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _PyIGL.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyIGL.vectord_push_back(self, x)

    def front(self):
        return _PyIGL.vectord_front(self)

    def back(self):
        return _PyIGL.vectord_back(self)

    def assign(self, n, x):
        return _PyIGL.vectord_assign(self, n, x)

    def resize(self, *args):
        return _PyIGL.vectord_resize(self, *args)

    def insert(self, *args):
        return _PyIGL.vectord_insert(self, *args)

    def reserve(self, n):
        return _PyIGL.vectord_reserve(self, n)

    def capacity(self):
        return _PyIGL.vectord_capacity(self)
    __swig_destroy__ = _PyIGL.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _PyIGL.vectord_swigregister
vectord_swigregister(vectord)

class vectors(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectors, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectors, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _PyIGL.vectors_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyIGL.vectors___nonzero__(self)

    def __bool__(self):
        return _PyIGL.vectors___bool__(self)

    def __len__(self):
        return _PyIGL.vectors___len__(self)

    def __getslice__(self, i, j):
        return _PyIGL.vectors___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyIGL.vectors___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyIGL.vectors___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyIGL.vectors___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyIGL.vectors___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyIGL.vectors___setitem__(self, *args)

    def pop(self):
        return _PyIGL.vectors_pop(self)

    def append(self, x):
        return _PyIGL.vectors_append(self, x)

    def empty(self):
        return _PyIGL.vectors_empty(self)

    def size(self):
        return _PyIGL.vectors_size(self)

    def swap(self, v):
        return _PyIGL.vectors_swap(self, v)

    def begin(self):
        return _PyIGL.vectors_begin(self)

    def end(self):
        return _PyIGL.vectors_end(self)

    def rbegin(self):
        return _PyIGL.vectors_rbegin(self)

    def rend(self):
        return _PyIGL.vectors_rend(self)

    def clear(self):
        return _PyIGL.vectors_clear(self)

    def get_allocator(self):
        return _PyIGL.vectors_get_allocator(self)

    def pop_back(self):
        return _PyIGL.vectors_pop_back(self)

    def erase(self, *args):
        return _PyIGL.vectors_erase(self, *args)

    def __init__(self, *args):
        this = _PyIGL.new_vectors(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _PyIGL.vectors_push_back(self, x)

    def front(self):
        return _PyIGL.vectors_front(self)

    def back(self):
        return _PyIGL.vectors_back(self)

    def assign(self, n, x):
        return _PyIGL.vectors_assign(self, n, x)

    def resize(self, *args):
        return _PyIGL.vectors_resize(self, *args)

    def insert(self, *args):
        return _PyIGL.vectors_insert(self, *args)

    def reserve(self, n):
        return _PyIGL.vectors_reserve(self, n)

    def capacity(self):
        return _PyIGL.vectors_capacity(self)
    __swig_destroy__ = _PyIGL.delete_vectors
    __del__ = lambda self: None
vectors_swigregister = _PyIGL.vectors_swigregister
vectors_swigregister(vectors)

class Mesh(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mesh, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mesh, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyIGL.delete_Mesh
    __del__ = lambda self: None

    def get_dim(self):
        return _PyIGL.Mesh_get_dim(self)

    def get_num_vertices(self):
        return _PyIGL.Mesh_get_num_vertices(self)

    def get_num_faces(self):
        return _PyIGL.Mesh_get_num_faces(self)

    def get_num_voxels(self):
        return _PyIGL.Mesh_get_num_voxels(self)

    def get_vertex(self, *args):
        return _PyIGL.Mesh_get_vertex(self, *args)

    def get_face(self, *args):
        return _PyIGL.Mesh_get_face(self, *args)

    def get_voxel(self, *args):
        return _PyIGL.Mesh_get_voxel(self, *args)

    def get_vertices(self, *args):
        return _PyIGL.Mesh_get_vertices(self, *args)

    def get_faces(self, *args):
        return _PyIGL.Mesh_get_faces(self, *args)

    def get_voxels(self, *args):
        return _PyIGL.Mesh_get_voxels(self, *args)

    def get_vertex_per_face(self):
        return _PyIGL.Mesh_get_vertex_per_face(self)

    def get_vertex_per_voxel(self):
        return _PyIGL.Mesh_get_vertex_per_voxel(self)

    def enable_connectivity(self):
        return _PyIGL.Mesh_enable_connectivity(self)

    def enable_vertex_connectivity(self):
        return _PyIGL.Mesh_enable_vertex_connectivity(self)

    def enable_face_connectivity(self):
        return _PyIGL.Mesh_enable_face_connectivity(self)

    def enable_voxel_connectivity(self):
        return _PyIGL.Mesh_enable_voxel_connectivity(self)

    def get_vertex_adjacent_vertices(self, vi):
        return _PyIGL.Mesh_get_vertex_adjacent_vertices(self, vi)

    def get_vertex_adjacent_faces(self, vi):
        return _PyIGL.Mesh_get_vertex_adjacent_faces(self, vi)

    def get_vertex_adjacent_voxels(self, vi):
        return _PyIGL.Mesh_get_vertex_adjacent_voxels(self, vi)

    def get_face_adjacent_faces(self, fi):
        return _PyIGL.Mesh_get_face_adjacent_faces(self, fi)

    def get_face_adjacent_voxels(self, fi):
        return _PyIGL.Mesh_get_face_adjacent_voxels(self, fi)

    def get_voxel_adjacent_faces(self, Vi):
        return _PyIGL.Mesh_get_voxel_adjacent_faces(self, Vi)

    def get_voxel_adjacent_voxels(self, Vi):
        return _PyIGL.Mesh_get_voxel_adjacent_voxels(self, Vi)

    def has_attribute(self, attr_name):
        return _PyIGL.Mesh_has_attribute(self, attr_name)

    def add_attribute(self, attr_name):
        return _PyIGL.Mesh_add_attribute(self, attr_name)

    def remove_attribute(self, attr_name):
        return _PyIGL.Mesh_remove_attribute(self, attr_name)

    def get_attribute(self, *args):
        return _PyIGL.Mesh_get_attribute(self, *args)

    def set_attribute(self, attr_name, attr_value):
        return _PyIGL.Mesh_set_attribute(self, attr_name, attr_value)

    def get_attribute_names(self):
        return _PyIGL.Mesh_get_attribute_names(self)
Mesh_swigregister = _PyIGL.Mesh_swigregister
Mesh_swigregister(Mesh)

class CellPartition(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CellPartition, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CellPartition, name)
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyIGL.CellPartition_create)
    else:
        create = _PyIGL.CellPartition_create
    if _newclass:
        create_raw = staticmethod(_PyIGL.CellPartition_create_raw)
    else:
        create_raw = _PyIGL.CellPartition_create_raw

    def __init__(self, vertices, faces):
        this = _PyIGL.new_CellPartition(vertices, faces)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def run(self):
        return _PyIGL.CellPartition_run(self)

    def get_vertices(self):
        return _PyIGL.CellPartition_get_vertices(self)

    def get_faces(self):
        return _PyIGL.CellPartition_get_faces(self)

    def get_source_faces(self):
        return _PyIGL.CellPartition_get_source_faces(self)

    def get_num_cells(self):
        return _PyIGL.CellPartition_get_num_cells(self)

    def get_cell_faces(self, cell_id):
        return _PyIGL.CellPartition_get_cell_faces(self, cell_id)

    def get_cells(self):
        return _PyIGL.CellPartition_get_cells(self)

    def get_num_patches(self):
        return _PyIGL.CellPartition_get_num_patches(self)

    def get_patches(self):
        return _PyIGL.CellPartition_get_patches(self)

    def get_winding_number(self):
        return _PyIGL.CellPartition_get_winding_number(self)
    __swig_destroy__ = _PyIGL.delete_CellPartition
    __del__ = lambda self: None
CellPartition_swigregister = _PyIGL.CellPartition_swigregister
CellPartition_swigregister(CellPartition)

def CellPartition_create(mesh):
    return _PyIGL.CellPartition_create(mesh)
CellPartition_create = _PyIGL.CellPartition_create

def CellPartition_create_raw(vertices, faces):
    return _PyIGL.CellPartition_create_raw(vertices, faces)
CellPartition_create_raw = _PyIGL.CellPartition_create_raw

class MinkowskiSum(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MinkowskiSum, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MinkowskiSum, name)
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyIGL.MinkowskiSum_create)
    else:
        create = _PyIGL.MinkowskiSum_create
    if _newclass:
        create_raw = staticmethod(_PyIGL.MinkowskiSum_create_raw)
    else:
        create_raw = _PyIGL.MinkowskiSum_create_raw

    def __init__(self, vertices, faces):
        this = _PyIGL.new_MinkowskiSum(vertices, faces)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def run(self, path):
        return _PyIGL.MinkowskiSum_run(self, path)

    def get_vertices(self):
        return _PyIGL.MinkowskiSum_get_vertices(self)

    def get_faces(self):
        return _PyIGL.MinkowskiSum_get_faces(self)
    __swig_destroy__ = _PyIGL.delete_MinkowskiSum
    __del__ = lambda self: None
MinkowskiSum_swigregister = _PyIGL.MinkowskiSum_swigregister
MinkowskiSum_swigregister(MinkowskiSum)

def MinkowskiSum_create(mesh):
    return _PyIGL.MinkowskiSum_create(mesh)
MinkowskiSum_create = _PyIGL.MinkowskiSum_create

def MinkowskiSum_create_raw(vertices, faces):
    return _PyIGL.MinkowskiSum_create_raw(vertices, faces)
MinkowskiSum_create_raw = _PyIGL.MinkowskiSum_create_raw


def load_MatrixF_DMAT(filename):
    return _PyIGL.load_MatrixF_DMAT(filename)
load_MatrixF_DMAT = _PyIGL.load_MatrixF_DMAT

def load_MatrixFr_DMAT(filename):
    return _PyIGL.load_MatrixFr_DMAT(filename)
load_MatrixFr_DMAT = _PyIGL.load_MatrixFr_DMAT

def load_MatrixI_DMAT(filename):
    return _PyIGL.load_MatrixI_DMAT(filename)
load_MatrixI_DMAT = _PyIGL.load_MatrixI_DMAT

def load_MatrixIr_DMAT(filename):
    return _PyIGL.load_MatrixIr_DMAT(filename)
load_MatrixIr_DMAT = _PyIGL.load_MatrixIr_DMAT

def save_MatrixF_DMAT(filename, M, in_ascii=False):
    return _PyIGL.save_MatrixF_DMAT(filename, M, in_ascii)
save_MatrixF_DMAT = _PyIGL.save_MatrixF_DMAT

def save_MatrixFr_DMAT(filename, M, in_ascii=False):
    return _PyIGL.save_MatrixFr_DMAT(filename, M, in_ascii)
save_MatrixFr_DMAT = _PyIGL.save_MatrixFr_DMAT

def save_MatrixI_DMAT(filename, M, in_ascii=False):
    return _PyIGL.save_MatrixI_DMAT(filename, M, in_ascii)
save_MatrixI_DMAT = _PyIGL.save_MatrixI_DMAT

def save_MatrixIr_DMAT(filename, M, in_ascii=False):
    return _PyIGL.save_MatrixIr_DMAT(filename, M, in_ascii)
save_MatrixIr_DMAT = _PyIGL.save_MatrixIr_DMAT
# This file is compatible with both classic and new-style classes.


