# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PyOuterHull')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PyOuterHull')
    _PyOuterHull = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyOuterHull', [dirname(__file__)])
        except ImportError:
            import _PyOuterHull
            return _PyOuterHull
        try:
            _mod = imp.load_module('_PyOuterHull', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PyOuterHull = swig_import_helper()
    del swig_import_helper
else:
    import _PyOuterHull
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

SHARED_PTR_DISOWN = _PyOuterHull.SHARED_PTR_DISOWN
class OuterHullEngine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OuterHullEngine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OuterHullEngine, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyOuterHull.OuterHullEngine_create)
    else:
        create = _PyOuterHull.OuterHullEngine_create
    __swig_destroy__ = _PyOuterHull.delete_OuterHullEngine
    __del__ = lambda self: None

    def run(self):
        return _PyOuterHull.OuterHullEngine_run(self)

    def set_mesh(self, vertices, faces):
        return _PyOuterHull.OuterHullEngine_set_mesh(self, vertices, faces)

    def get_vertices(self):
        return _PyOuterHull.OuterHullEngine_get_vertices(self)

    def get_faces(self):
        return _PyOuterHull.OuterHullEngine_get_faces(self)

    def get_outer_hull_layers(self):
        return _PyOuterHull.OuterHullEngine_get_outer_hull_layers(self)

    def get_face_is_flipped(self):
        return _PyOuterHull.OuterHullEngine_get_face_is_flipped(self)

    def get_ori_face_indices(self):
        return _PyOuterHull.OuterHullEngine_get_ori_face_indices(self)
OuterHullEngine_swigregister = _PyOuterHull.OuterHullEngine_swigregister
OuterHullEngine_swigregister(OuterHullEngine)

def OuterHullEngine_create(engine_name):
    return _PyOuterHull.OuterHullEngine_create(engine_name)
OuterHullEngine_create = _PyOuterHull.OuterHullEngine_create

# This file is compatible with both classic and new-style classes.


