# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PySelfIntersection')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PySelfIntersection')
    _PySelfIntersection = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PySelfIntersection', [dirname(__file__)])
        except ImportError:
            import _PySelfIntersection
            return _PySelfIntersection
        try:
            _mod = imp.load_module('_PySelfIntersection', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PySelfIntersection = swig_import_helper()
    del swig_import_helper
else:
    import _PySelfIntersection
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

SHARED_PTR_DISOWN = _PySelfIntersection.SHARED_PTR_DISOWN
class SelfIntersectionResolver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SelfIntersectionResolver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SelfIntersectionResolver, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PySelfIntersection.SelfIntersectionResolver_create)
    else:
        create = _PySelfIntersection.SelfIntersectionResolver_create
    __swig_destroy__ = _PySelfIntersection.delete_SelfIntersectionResolver
    __del__ = lambda self: None

    def set_mesh(self, vertices, faces):
        return _PySelfIntersection.SelfIntersectionResolver_set_mesh(self, vertices, faces)

    def run(self):
        return _PySelfIntersection.SelfIntersectionResolver_run(self)

    def get_vertices(self):
        return _PySelfIntersection.SelfIntersectionResolver_get_vertices(self)

    def get_faces(self):
        return _PySelfIntersection.SelfIntersectionResolver_get_faces(self)

    def get_face_sources(self):
        return _PySelfIntersection.SelfIntersectionResolver_get_face_sources(self)
SelfIntersectionResolver_swigregister = _PySelfIntersection.SelfIntersectionResolver_swigregister
SelfIntersectionResolver_swigregister(SelfIntersectionResolver)

def SelfIntersectionResolver_create(engine_name):
    return _PySelfIntersection.SelfIntersectionResolver_create(engine_name)
SelfIntersectionResolver_create = _PySelfIntersection.SelfIntersectionResolver_create

# This file is compatible with both classic and new-style classes.


