# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PyTetrahedronization')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PyTetrahedronization')
    _PyTetrahedronization = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyTetrahedronization', [dirname(__file__)])
        except ImportError:
            import _PyTetrahedronization
            return _PyTetrahedronization
        try:
            _mod = imp.load_module('_PyTetrahedronization', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PyTetrahedronization = swig_import_helper()
    del swig_import_helper
else:
    import _PyTetrahedronization
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

SHARED_PTR_DISOWN = _PyTetrahedronization.SHARED_PTR_DISOWN
class TetrahedronizationEngine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TetrahedronizationEngine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TetrahedronizationEngine, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    if _newclass:
        create = staticmethod(_PyTetrahedronization.TetrahedronizationEngine_create)
    else:
        create = _PyTetrahedronization.TetrahedronizationEngine_create
    __swig_destroy__ = _PyTetrahedronization.delete_TetrahedronizationEngine
    __del__ = lambda self: None

    def run(self):
        return _PyTetrahedronization.TetrahedronizationEngine_run(self)

    def set_vertices(self, vertices):
        return _PyTetrahedronization.TetrahedronizationEngine_set_vertices(self, vertices)

    def set_faces(self, faces):
        return _PyTetrahedronization.TetrahedronizationEngine_set_faces(self, faces)

    def set_edge_size(self, val):
        return _PyTetrahedronization.TetrahedronizationEngine_set_edge_size(self, val)

    def set_face_size(self, val):
        return _PyTetrahedronization.TetrahedronizationEngine_set_face_size(self, val)

    def set_cell_radius_edge_ratio(self, val):
        return _PyTetrahedronization.TetrahedronizationEngine_set_cell_radius_edge_ratio(self, val)

    def set_cell_size(self, val):
        return _PyTetrahedronization.TetrahedronizationEngine_set_cell_size(self, val)

    def get_vertices(self):
        return _PyTetrahedronization.TetrahedronizationEngine_get_vertices(self)

    def get_faces(self):
        return _PyTetrahedronization.TetrahedronizationEngine_get_faces(self)

    def get_voxels(self):
        return _PyTetrahedronization.TetrahedronizationEngine_get_voxels(self)
TetrahedronizationEngine_swigregister = _PyTetrahedronization.TetrahedronizationEngine_swigregister
TetrahedronizationEngine_swigregister(TetrahedronizationEngine)

def TetrahedronizationEngine_create(engine_name):
    return _PyTetrahedronization.TetrahedronizationEngine_create(engine_name)
TetrahedronizationEngine_create = _PyTetrahedronization.TetrahedronizationEngine_create

# This file is compatible with both classic and new-style classes.


